version: '3.7'

services:
    quitstore:
      image: aksw/quitstore
      container_name: quitstore
      environment:
        - VIRTUAL_HOST=quit.ontopad.aksw.org
        - LETSENCRYPT_HOST=quit.ontopad.aksw.org
        - LETSENCRYPT_EMAIL=arndtn@gmail.com
        - QUIT_TARGETDIR=/data
      volumes:
        - data:/data
      ports:
        - 8082:8080

    ontopad:
      image: aksw/ontopad
      container_name: ontopad
      environment:
        - VIRTUAL_HOST=demo.ontopad.aksw.org
        - LETSENCRYPT_HOST=demo.ontopad.aksw.org
        - LETSENCRYPT_EMAIL=arndtn@gmail.com
        - QUIT_QUERY=https://quit.ontopad.aksw.org
        - QUIT_UPDATE=https://quit.ontopad.aksw.org
      ports:
        - 8080:8080

volumes:
    data: {}
