version: '3.3'

services:
    quitstore:
      image: aksw/quitstore
      container_name: ontopad_quitstore
      environment:
        - VIRTUAL_HOST=quit.ontopad.aksw.org
        - LETSENCRYPT_HOST=quit.ontopad.aksw.org
        - LETSENCRYPT_EMAIL=arndtn@gmail.com
        - QUIT_TARGETDIR=/data
      volumes:
        - data:/data

    ontopad:
      image: aksw/ontopad
      container_name: ontopad_demo
      environment:
        - VIRTUAL_HOST=demo.ontopad.aksw.org
        - LETSENCRYPT_HOST=demo.ontopad.aksw.org
        - LETSENCRYPT_EMAIL=arndtn@gmail.com
        - QUIT_QUERY=https://quit.ontopad.aksw.org
        - QUIT_UPDATE=https://quit.ontopad.aksw.org

volumes:
    data: {}
