version: '3.3'

services:
    quitstore:
      image: aksw/quitstore
      container_name: ontopad_quitstore
      restart: unless-stopped
      environment:
        - VIRTUAL_HOST=quit.ontopad.aksw.org
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=quit.ontopad.aksw.org
        - LETSENCRYPT_EMAIL=arndtn@gmail.com
        - QUIT_TARGETDIR=/data
      volumes:
        - data:/data
      network_mode: bridge

    ontopad:
      image: aksw/ontopad
      container_name: ontopad_demo
      restart: unless-stopped
      environment:
        - VIRTUAL_HOST=demo.ontopad.aksw.org
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=demo.ontopad.aksw.org
        - LETSENCRYPT_EMAIL=arndtn@gmail.com
        - QUIT_URL=https://quit.ontopad.aksw.org
      network_mode: bridge

volumes:
    data: {}
